document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/css/20190313-app-block.css?122018\' media=\'all\' alt=\'移动端底部浮动弹窗 akdydh\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/css/index3.css?122018\' media=\'all\' alt=\'顶部横排logo\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/css/ulc.css?0302\' id=\'ulc_main-css\' media=\'all\'>");
document.writeln("<!-- <link rel=\'stylesheet\' type=\'text/css\' href=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/css/csshake.min.css?122018\' media=\'all\'> -->");
document.writeln("<!-- <link rel=\'stylesheet\' type=\'text/css\' href=\'https://s0.pstatp.com/cdn/expire-1-y/csshake/1.5.0/csshake.min.css?0506\' media=\'all\'> -->");
document.writeln("<!-- <link rel=\'stylesheet\' type=\'text/css\' href=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/css/font-awesome.min.css?122018\' id=\'font-awesome-css\' media=\'all\' alt=\'表格左上角icon\'> -->");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/css/font-awesome.min.css?0506\' id=\'font-awesome-css\' media=\'all\' alt=\'表格左上角icon\'>");
document.writeln("<!-- <link rel=\'stylesheet\' type=\'text/css\' href=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/css/jquery.webui-popover.min.css?122018\' id=\'jquery.webui-popover-css\' media=\'all\'> -->");
document.writeln("<!-- <link rel=\'stylesheet\' type=\'text/css\' href=\'https://s1.pstatp.com/cdn/expire-1-y/webui-popover/2.1.15/jquery.webui-popover.min.css?0506\' id=\'jquery.webui-popover-css\' media=\'all\'> -->");
document.writeln("<style>");
document.writeln("    .iconbox img {");
document.writeln("    border-radius: 50%;");
document.writeln("}");
document.writeln("");
document.writeln(".icon_box img:hover {");
document.writeln("    background: rgba(255, 255, 255, .05);");
document.writeln("    -webkit-transform: scale(.93);");
document.writeln("    -moz-transform: scale(.93);");
document.writeln("    -ms-transform: scale(.93);");
document.writeln("    transform: scale(.93);");
document.writeln("    color: #fff");
document.writeln("}");
document.writeln("");
document.writeln("input#ulc-search-483:hover {");
document.writeln("    border: 1px solid #dddddd;");
document.writeln("}");
document.writeln("");
document.writeln(".back-top-btn {");
document.writeln("    position: fixed;");
document.writeln("    bottom: 10px;");
document.writeln("    right: 20px;");
document.writeln("    z-index: 999;");
document.writeln("    transition: all .5s;");
document.writeln("}");
document.writeln("");
document.writeln("input#ulc-search-483 {");
document.writeln("    background-color: rgb(241, 243, 244);");
document.writeln("    border-radius: 22px;");
document.writeln("    border-image-repeat: stretch;");
document.writeln("    border-image-slice: 100%;");
document.writeln("    border-image-source: none;");
document.writeln("    border-image-width: 1;");
document.writeln("    box-shadow: none;");
document.writeln("    cursor: text;");
document.writeln("    display: inline-block;");
document.writeln("    font-family: arial, sans-serif;");
document.writeln("    font-size: 18px;");
document.writeln("    font-weight: 400;");
document.writeln("    height: 44px;");
document.writeln("    line-height: 36px;");
document.writeln("    max-width: 80%;");
document.writeln("    opacity: 1;");
document.writeln("    position: relative;");
document.writeln("    transition-duration: 0.2s;");
document.writeln("    transition-property: opacity;");
document.writeln("    transition-timing-function: ease;");
document.writeln("    border-width: 0px;");
document.writeln("    outline: none;");
document.writeln("    padding: 0 22px;");
document.writeln("    width: 516px;");
document.writeln("}");
document.writeln("");
document.writeln(".panel {");
document.writeln("    width: 100% !important;");
document.writeln("    text-align: center;");
document.writeln("}");
document.writeln("");
document.writeln(".icon_box {");
document.writeln("    width: 70px !important;");
document.writeln("}");
document.writeln("");
document.writeln(".icon_title {");
document.writeln("    width: 70px !important;");
document.writeln("    margin-left: auto;");
document.writeln("}");
document.writeln("");
document.writeln(".footer {");
document.writeln("    width: 100%;");
document.writeln("    padding-right: 15px;");
document.writeln("    padding-left: 15px;");
document.writeln("    margin-right: auto;");
document.writeln("    margin-left: auto;");
document.writeln("    margin-top: -80px;");
document.writeln("}");
document.writeln("");
document.writeln("#copyrights {");
document.writeln("    background-color: #fff;");
document.writeln("    font-size: 14px;");
document.writeln("}");
document.writeln("");
document.writeln("#copyrights .col_half {");
document.writeln("    margin-bottom: 0 !important;");
document.writeln("    color: #828282");
document.writeln("}");
document.writeln("");
document.writeln("#copyrights a:first-child {");
document.writeln("    margin-left: 0");
document.writeln("}");
document.writeln("");
document.writeln(".copyright-links a {");
document.writeln("    display: inline-block;");
document.writeln("    margin: 0 3px;");
document.writeln("    color: #696969;");
document.writeln("    border-bottom: 1px dotted #696969");
document.writeln("}");
document.writeln("");
document.writeln(".col_last {");
document.writeln("    margin-right: 0 !important;");
document.writeln("    float: right;");
document.writeln("    clear: right");
document.writeln("}");
document.writeln("");
document.writeln(".tright {");
document.writeln("    text-align: right !important");
document.writeln("}");
document.writeln("");
document.writeln(".copyrights-menu {");
document.writeln("    margin-bottom: 10px");
document.writeln("}");
document.writeln("");
document.writeln(".copyrights-menu a {");
document.writeln("    font-size: 14px;");
document.writeln("    margin: 0 10px;");
document.writeln("    border-bottom: 0 !important");
document.writeln("}");
document.writeln("");
document.writeln(".copyright-links a {");
document.writeln("    display: inline-block;");
document.writeln("    margin: 0 3px;");
document.writeln("    color: #828282;");
document.writeln("    border-bottom: 1px dotted #444");
document.writeln("}");
document.writeln("");
document.writeln(".clearfix::after {");
document.writeln("    display: block;");
document.writeln("    clear: both;");
document.writeln("    content: \'\'");
document.writeln("}");
document.writeln("");
document.writeln("*,");
document.writeln("*::before,");
document.writeln("*::after {");
document.writeln("    box-sizing: border-box");
document.writeln("}");
document.writeln("");
document.writeln(".copyright-links a:hover {");
document.writeln("    color: #555;");
document.writeln("    border-bottom: 1px solid #666");
document.writeln("}");
document.writeln("");
document.writeln(".copyright-links a {");
document.writeln("    text-decoration: none");
document.writeln("}");
document.writeln("");
document.writeln(".topbar {");
document.writeln("    height: 35px;");
document.writeln("    overflow: hidden;");
document.writeln("    width: 100%;");
document.writeln("    background: rgb(241, 243, 244);");
document.writeln("    font-size: 13px;");
document.writeln("    transition-duration: 0.2s;");
document.writeln("    transition-property: opacity;");
document.writeln("    transition-timing-function: ease;");
document.writeln("}");
document.writeln("");
document.writeln(".topbar a {");
document.writeln("    text-decoration: none;");
document.writeln("    color: #333;");
document.writeln("}");
document.writeln("");
document.writeln(".topbar a:hover {");
document.writeln("    color: #FF7DB1;");
document.writeln("}");
document.writeln("");
document.writeln(".left-side li {");
document.writeln("    float: left;");
document.writeln("    padding-right: 7px;");
document.writeln("    line-height: 11px;");
document.writeln("    list-style: none;");
document.writeln("}");
document.writeln("");
document.writeln(".collect {");
document.writeln("    position: fixed;");
document.writeln("    top: 36px;");
document.writeln("    right: 20%;");
document.writeln("    padding: 15px 20px 15px 65px;");
document.writeln("    border-radius: 10px;");
document.writeln("    border: 1px solid #eee;");
document.writeln("    box-shadow: 0 0 8px rgba(0, 0, 0, .15);");
document.writeln("}");
document.writeln("");
document.writeln(".collect .arrow {");
document.writeln("    position: absolute;");
document.writeln("    width: 20px;");
document.writeln("    height: 12px;");
document.writeln("    display: inline-block;");
document.writeln("    background: url(https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/images/arrow.png) center top no-repeat;");
document.writeln("    top: -12px;");
document.writeln("    right: 30px;");
document.writeln("}");
document.writeln("");
document.writeln(".collect .star {");
document.writeln("    position: absolute;");
document.writeln("    width: 36px;");
document.writeln("    height: 36px;");
document.writeln("    display: inline-block;");
document.writeln("    background: url(https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/images/star.png) center center no-repeat;");
document.writeln("    left: 15px;");
document.writeln("    top: 15px;");
document.writeln("}");
document.writeln("");
document.writeln(".collect_focus {");
document.writeln("    padding: 0 10px;");
document.writeln("    color: #FF7DB1;");
document.writeln("    font-weight: bold;");
document.writeln("    font-size: 15px;");
document.writeln("}");
document.writeln("</style>");