document.writeln("");
document.writeln("    <div class=\'topbar\'>");
document.writeln("        <div class=\'left-side\'>");
document.writeln("            <ul>");
document.writeln("                <li><a href=\'https://www.cavhot.com/?www.cav.ooo0516-1650\' style=\'color: red\'><b>请收藏本站便于回访</b></a></li>");
document.writeln("                <li><a href=\'https://www.cav.ooo/?www.cav.ooo\'>主站CAV.OOO</a></li>");
document.writeln("                <li><a href=\'https://www.cav.icu/?www.cav.ooo\'>备站CAV.icu</a></li>");
document.writeln("                <li><a href=\'https://github.com/avhot/www.cav.ooo\' style=\'color: red\'><b>永久地址</b></a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'ct_body\'>");
document.writeln("        <div class=\'ct_content\'>");
document.writeln("            <div class=\'ct_head shake-slow\'>");
document.writeln("                <a href=\'https://www.cav.ooo/\' class=\'logo\'><img src=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/logo1.png\' alt=\'人生苦短，及时行乐\' title=\'人生苦短，及时行乐\'><span></span></a>");
document.writeln("            </div>");
document.writeln("            <div class=\'sc_panel\'>");
document.writeln("                <form action=\'/search\' id=\'f\' method=\'get\'>");
document.writeln("                    <font color=\'red\'>请收藏本站及推荐站点中还能访问的网址！</font><br>电脑端可使用<span class=\'collect_focus\'>CTRL + F</span>搜索想要的网站");
document.writeln("                </form>");
document.writeln("                <br>");
document.writeln("                <a target=\'_blank\' href=\'https://app.cav.ooo/?www.cav.ooo\'><img src=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/images/ad1.jpg?v=0320\' width=\'70%\'></a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div id=\'ulc-483\' class=\'ulc-grid ulc-style-flat ulc-grid-columns-3\'>");
document.writeln("        <div class=\'panel\'>");
document.writeln("            <div class=\'icon_box\'>");
document.writeln("                <a href=\'./yabo/\' target=\'_blank\'>");
document.writeln("                    <img src=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/images/yabo.png?0511-1706\'>");
document.writeln("                    <div class=\'icon_title\' style=\'color:blue\'>&#20122;&#21338;体育</div>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("            <div class=\'icon_box\'>");
document.writeln("                <a href=\'https://at.umtrack.com/Da0Hfa?cid=22987&clickid={{clickid}}\' target=\'_blank\'>");
document.writeln("                    <img src=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/images/tiyu.png?0302\'>");
document.writeln("                    <div class=\'icon_title\' style=\'color:red\'>体育|&#30334;&#23478;&#20048;</div>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("            <div class=\'icon_box\'>");
document.writeln("                <a href=\'https://at.umtrack.com/eemSbm?cid=22987&clickid={{clickid}}\' target=\'_blank\'>");
document.writeln("                    <img src=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/images/wuta.png?0511\'>");
document.writeln("                    <div class=\'icon_title\' style=\'color:red\'>&#30495;&#38065;&#26827;&#29260;</div>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("            <div class=\'icon_box\'>");
document.writeln("                <a href=\'https://www.akdydh.com/?www.cav.ooo.nav1\' title=\'免费VIP热播电视剧在线观看\' target=\'_blank\'>");
document.writeln("                    <img src=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/images/dd.png?0302\'>");
document.writeln("                    <div class=\'icon_title\'>电影导航</div>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("            <div class=\'icon_box\'>");
document.writeln("                <a href=\'http://mimi84.xyz:6262/?channelCode=EJ5KD\' target=\'_blank\'>");
document.writeln("                    <img src=\'https://cdn.jsdelivr.net/gh/avhot/cdn@latest/www.cav.ooo/images/mmzhibo.png?0513-1810\'>");
document.writeln("                    <div class=\'icon_title\' p=\'6.0/zc\' style=\'color:red\'>&#27880;&#20876;&#25784;&#22899;&#20027;&#25773;</div>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("        </div>");